### PR TITLE
Feature: Support more CI/CD platforms

### PR DESCRIPTION
**Pull request by picccard**
# Pull Request

## Issue

Add option to choose CI/CD platform (Github | Azure Devops). Default beeing Github.

Issue #, if available:

## Description

Description of changes:
- added new parameter `alzCicdPlatform` to New-ALZEnvironment.ps1
- added ref to accelerator azure pipelines in asset file for ALZ v0.14.0
- moved accelerator readme to be the first reference 
- moved yml files for CI/CD to its own property in the config file 

## Breaking changes
This feature will not break any functionality, as the parameter has 'github' as default.
If you were to run the accelerator with the parameter set to 'azuredevops' you would only see the [this warning](https://github.com/Azure/ALZ-PowerShell-Module/blob/11c0b6f66bc3f31de660167f237ddbc28370f553/src/ALZ/Private/Copy-ALZParametersFile.ps1#L29) telling you the files are not found and end up without any .azuredevops folder in the desired OutputDirectory / alzEnvironmentDestination

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by lovelysandwich** [comment]
@picccard 
Huge thanks for submitting this PR - we're just waiting on a colleague @oZakari to give it the once over.

Small note - there's a test failure which seems to have cropped up.  If you're able to address that we'd be very grateful.

**Comment by picccard** [comment]
@lovelysandwich
The tests runs without errors now.

Also for @oZakari:
Since `Copy-ALZParametersFile` now copies parameterfiles, pipelines, pipeline scripts and the accelerator/readme.md, should it be changed to something more general like `Copy-ALZFile`?

**Comment by oZakari** [comment]
> @lovelysandwich The tests runs without errors now.
> 
> Also for @oZakari: Since `Copy-ALZParametersFile` now copies parameterfiles, pipelines, pipeline scripts and the accelerator/readme.md, should it be changed to something more general like `Copy-ALZFile`?

Thanks @piccard, and I think my network connection must've dropped when I initially attempted to respond. Now that your Azure DevOps PR is in ALZ-Bicep, just working with the team internally (should be finalized tomorrow) to determine best approach for keeping the releases in-sync.

**Comment by oZakari** [comment]
Sorry @piccard, we had to rush to get a fix out for an issue in ALZ-Bicep, so I had to just create a separate PR with some necessary changes for Azure DevOps support.

**Pull request closed without merging**
