### PR TITLE
enhancement: relocate bootstrap modules

### PR DESCRIPTION
**Pull request by jaredfholgate**
# Pull Request

## Issue

Issue #, if available: N/A

## Description

This PR is a significant refactor to de-couple bootstrap and starter modules. It moves to a configuration based approach for shared inputs and have many other enhancements to the user experience.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@oZakari, @luke-taylor and @jtracey93 I think this PR is now ready for review. I have some work left to do on the bootstrap repo in terms of enhancing the documentation for the json, but I believe the PowerShell is now functionally complete and the docs are up to date. It would be great if you could double check that the Bicep behaviour is correct and as expected. Especially when running it as it is run today (i.e. `New-ALZEnvironment -o "." -i "bicep" -c "github"`).

I intend to submit separate documentation PR's to each of the supporting repos to update them to match the new naming and upgrade process, but in the meantime the existing documentation should still work for the new version with the exception of the Bicep upgrade process.

**Comment by jaredfholgate** [comment]
> @oZakari, @luke-taylor and @jtracey93 I think this PR is now ready for review. I have some work left to do on the bootstrap repo in terms of enhancing the documentation for the json, but I believe the PowerShell is now functionally complete and the docs are up to date. It would be great if you could double check that the Bicep behaviour is correct and as expected. Especially when running it as it is run today (i.e. `New-ALZEnvironment -o "." -i "bicep" -c "github"`).
> 
> I intend to submit separate documentation PR's to each of the supporting repos to update them to match the new naming and upgrade process, but in the meantime the existing documentation should still work for the new version with the exception of the Bicep upgrade process.

I do appreciate there are a lot of changes to the code here, so difficult to peer review from that perspective, but hopefully an end to end test will be sufficient to show it works as expected.

If you do have any specific questions about the code I can of course answer them.

**Review by oZakari — APPROVED** [review]
LGTM 👍🏼

**Comment by jaredfholgate** [comment]
Merging this release to be able to run end to end testing with alpha. Will not publish the full release until e2e tests are passing.

**Pull request merged**
