### PR TITLE
bug: fix switch and os selector

### PR DESCRIPTION
**Pull request by jaredfholgate**
# Pull Request

## Issue

Issue #, if available: #71, #73, and #74

## Description

Description of changes: Fix issues with downloading the HCL parser and running it on MacOS and Linux. Also solve a potential issue where Terraform runs despite bicep being selected.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@matt-FFFFFF and @oZakari There is limited testing I can do on this due to lacking a Mac, but I have tested in Linux and works as expected. However in my environment the file is already set as executable when it downloads, so unsure if my testing is valid.

I wish there was a PowerShell native HCL parser, but only libraries I can find are golang. I could write something bespoke, but was trying to avoid that. I also want to avoid storing binaries in source control. We might need to publish this for Matt to test it properly, sorry. I will also try to find someone with a Mac once it is published.

**Comment by matt-FFFFFF** [comment]
@jaredfholgate I have a Mac! We can also run GH actions using macOS runners.

Thank you for the speedy response here.

Hth tomorrow

**Comment by jaredfholgate** [comment]
> @jaredfholgate I have a Mac! We can also run GH actions using macOS runners.
> 
> Thank you for the speedy response here.
> 
> Hth tomorrow  

@matt-FFFFFF and @oZakari I am going look at writing some cross OS pester tests and an associated action for that particular function later today. If it is urgent you can merge this PR today and will add them to a separate one.

**Comment by matt-FFFFFF** [comment]
Hi @jaredfholgate @oZakari 

Confirmed this branch is working on WSL:

image

Checking MacOS now

**Comment by matt-FFFFFF** [comment]
Hi @jaredfholgate and @oZakari 

Confirmed working on MacOS

image

Please can we merge this? I was hoping to use it for a conference demo next week!

**Review by matt-FFFFFF — APPROVED** [review]

**Review by jtracey93 — APPROVED** [review]

**Comment by jtracey93** [comment]
@matt-FFFFFF  merged and new release will be out shortly of the module, please update it locally in about 30 mins :)

**Pull request merged**
