### PR TITLE
Fix bug in bicep path

### PR DESCRIPTION
**Pull request by jaredfholgate**
# Pull Request

## Issue

N/A

## Description

Fix an incorrect path

## Testing

You can see the Bicep tests passing here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/8375595350

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
Hi @oZakari. I found this bug in live when I ran the e2e tests. Will need to get the patch out ASAP.

**Review by sebassem — APPROVED** [review]
LGTM

**Comment by jaredfholgate** [comment]
I am going to go ahead and merge this and release without an approving review given the bicep accelerator is currently broken.

**Comment by oZakari** [comment]
Thanks for jumping on that @jaredfholgate, much appreciated!

**Pull request merged**
