### PR TITLE
Adding logic to add availability zones in parameters files for the networking platform resources depending on the selected region

### PR DESCRIPTION
**Pull request by sebassem**
# Pull Request

## Issue

Issue #103 and #102

## Description

Adding a new private function to determine the availability zones for the selected regions and edit the parameters files of the relevant networking modules to include them by default.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Review by oZakari — COMMENTED** [review]
Hey @sebassem, this works perfect from my initial testing! What are your thoughts on potentially adding a unit test for this function? I can't see us modifying this function long term, but just curious if you have any thoughts.

**Comment by sebassem** [comment]
> Hey @sebassem, this works perfect from my initial testing! What are your thoughts on potentially adding a unit test for this function? I can't see us modifying this function long term, but just curious if you have any thoughts.

sure thing , I can give it a try and see if its easy to implement.

**Comment by sebassem** [comment]
@oZakari I added a unit test for the function, please let me know if its ok

**Comment by jaredfholgate** [comment]
Hi @sebassem. I just saw this pull request is in progress. I have been working on a major refactor and have most likely broken your work, but given it looks like this is Bicep specific, you should be able to update the code to work with the new code base. Let me know if you need help though and apologies for pipping you to the post with my changes.

**Comment by sebassem** [comment]
> Hi @sebassem. I just saw this pull request is in progress. I have been working on a major refactor and have most likely broken your work, but given it looks like this is Bicep specific, you should be able to update the code to work with the new code base. Let me know if you need help though and apologies for pipping you to the post with my changes.

No worries @jaredfholgate I just created a new branch of the new changes and submitted a [PR](https://github.com/Azure/ALZ-PowerShell-Module/pull/108)

**Pull request closed without merging**
