### PR TITLE
feature: implement terraform

### PR DESCRIPTION
**Pull request by jaredfholgate**
# Pull Request

## Issue

N/A

## Description

The PR is to add Terraform functionality to the accelerator module without making any breaking changes to Bicep. The Terraform accelerator module is being built out in a separate repository.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@jtracey93 I have marked this PR ready for review as I think it ready to have some eyes on it. However, the associated alz repo is not complete yet and documentation is not complete, so not sure if you want to release this yet.

**Comment by oZakari** [comment]
Hey @jaredfholgate, nice work with this! 

I did merge a few changes as well as fixed a couple of small things that were causing issues on the Bicep side. 

I did notice that when testing using Terraform and specifying GitHub, that there were some Terraform errors specifying missing arguments (see screenshot below that includes some of the errors). I didn't get these same messages when specifiy Azure DevOps for the cicd parameter.

image

**Comment by jaredfholgate** [comment]
> Hey @jaredfholgate, nice w@ ork with this! 
> 
> I did merge a few changes as well as fixed a couple of small things that were causing issues on the Bicep side. 
> 
> I did notice that when testing using Terraform and specifying GitHub, that there were some Terraform errors specifying missing arguments (see screenshot below that includes some of the errors). I didn't get these same messages when specifiy Azure DevOps for the cicd parameter. Wasn't sure if it was specific to this module or the Terraform accelerator module but thought I would call it out.
> 
> image
> 

Thanks for fixing those bugs. GitHub is still a work in progress, should be there today or tomorrow. Will let you know.

**Comment by jaredfholgate** [comment]
@oZakari I made some further changes to simplify the config and get the subscription ids required for the bootstrap.

I have now tested the 3 scenarios end to end:

- Azure DevOps with Workload identity federations
- Azure DevOps with Managed service identity
- GitHub

Instructions for use are here: https://github.com/Azure/alz-terraform-accelerator/wiki/%5BUser-Guide%5D-Quick-Start

I think we are now in a position to merge and release this PR.

**Comment by jaredfholgate** [comment]
@oZakari I added one more commit as I realised I needed to support end to end testing, so needed a way to override the user inputs with minimal impact on the overall process. Apologies for lumping all the changes into one PR, but that is everything we need now for Terraform and to be able to acceptance test it properly using the module.

**Comment by oZakari** [comment]
Sounds great @jaredfholgate, I'll go through the rest of the changes tomorrow afternoon.

**Review by oZakari — APPROVED** [review]
This looks good to me! Good idea for overriding the config with the JSON file as well.

**Pull request merged**
